# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 912e14d8742c466fcd39889d7cf5cff5b6f4295cdc9572a484ce4c79de62455868868ed1ecf3c113ac01fae21950238c9d8adcbaa2b0aa469c29d3ad52b75cd9

test:
  secret_key_base: b84eb058c507043742db48d0255368332aa2bf748aef9d5e41c069ff6000f85f6c84abb1fba3b719ebcd666c8ea7e7c367574cc085a0ee83745f858bbe3acf3d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
